feat: create check init deploy reusable workflow
Orfium/orfium-github-actions pull request #113
Opened 2024-03-20 12:15 UTC by anmarkoulis

# Orfium GitHub Actions

## Description

[BEC-459](https://orfium.atlassian.net/browse/BEC-459)

## Checklist

- [ ] I have reviewed my code and checked that there are no unrelated changes in this pull request
- [ ] I have created a JIRA ticket describing the purpose of this pull request
- [ ] I have checked if the changes to the templates are breaking or have contacted the DevOps team for feedback
- [ ] I have updated the template with the Actionlint Format guidelines: [Actionlint](https://github.com/rhysd/actionlint#readme). Information on how to do that are provided on the CONTRIBUTING.md file under docs/ folder.

2024-03-20 12:33 UTC, Aloutsis commented on .github/workflows/check-init-deploy.yml
> +    permissions:
I don't think that we need those permissions here anymore. Since we migrated to Enterprise, those come directly from the caller, not the callee; so, we can remove them.

2024-03-20 12:35 UTC, anmarkoulis commented on .github/workflows/check-init-deploy.yml
> +    permissions:
Nice, will remove them and check what happens

2024-03-20 12:49 UTC, Aloutsis approved these changes
Looks good

2024-03-20 13:28 UTC, anmarkoulis commented
@Aloutsis works like a charm!

2024-03-21 09:23 UTC, chaidosk requested changes

2024-03-21 09:23 UTC, chaidosk commented on .github/workflows/check-init-deploy.yml
> +          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
@anmarkoulis Do we need AWS_ACCOUNT_ID and AWS_ACCOUNT_NAME?

2024-03-21 09:26 UTC, Aloutsis commented on .github/workflows/check-init-deploy.yml
> +          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
That comes from us. We don't need it, per se, but, we have it as mandatory so that people can quickly know which account they are deploying to as it's too difficult to remember all those 12-digit account ids. That is why we also check whether it is there or not; to force people to not forget it.

2024-03-21 10:31 UTC, chaidosk approved these changes

2024-03-21 11:46 UTC, merged